repos:
    # - repo: https://github.com/pycqa/isort
    #   rev: 5.13.2
    #   hooks:
    #       - id: isort
    #         name: isort (python)
    # - repo: https://github.com/ambv/black
    #   rev: 24.4.2
    #   hooks:
    #       - id: black

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0 # Use the latest version
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://github.com/pycqa/flake8
      rev: 6.1.0 # Use the latest version available
      hooks:
          - id: flake8
