# Generated by Django 4.2.20 on 2025-03-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredient", "0001_initial"),
        ("recipe", "0002_recipe_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(to="ingredient.ingredient"),
        ),
    ]
