# Generated by Django 4.2.20 on 2025-04-01 06:44

import recipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_recipe_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                null=True, upload_to=recipe.models.recipe_image_file_path
            ),
        ),
    ]
